export type ThemeOption = { id: string; code: string; name: string }
export type Profile = { nickname: string; profileImageUrl: string | null; bio: string | null; userTypes: string[]; preferredDistance: string | null; preferredDifficulty: string | null; createdAt: string; accountStatus: string }
export type ProfileUpdate = Pick<Profile, 'nickname' | 'profileImageUrl' | 'bio' | 'userTypes' | 'preferredDistance' | 'preferredDifficulty'> & { themeIds?: string[] }
export type Dashboard = { profile: Profile; totalDistanceKm: number; completionCount: number; uniqueCourseCount: number }
export type RunRecord = { id: string; courseId: string | null; courseName: string | null; courseType: 'RUNNING_COURSE' | 'SPOT_COURSE' | null; thumbnailImageUrl: string | null; distanceKm: number; durationSeconds: number; averagePace: number | null; startedAt: string }
export type Visit = { id: string; waypointId: string; courseId: string; courseName: string; name: string; description: string | null; imageUrl: string | null; visitedAt: string; orderIndex: number; latitude: number; longitude: number }
export type RunRouteCoordinate = { lat: number; lng: number }
export type RunWaypoint = { id: string; name: string; kakaoPlaceId: string | null; lat: number; lng: number; orderIndex: number; distanceFromStartKm: number | null; description: string | null; tourContentId: string | null; tourContentTypeId: string | null }
export type RunRecordDetail = RunRecord & { courseDescription: string | null; courseDifficulty: 'LOW' | 'MID' | 'HIGH' | null; runningMode: 'COURSE_SELECT' | 'COURSE_CREATE' | 'FREE_RUN'; calories: number | null; elevationGainM: number | null; endedAt: string; recordedRouteCoordinates: RunRouteCoordinate[]; plannedRouteCoordinates: RunRouteCoordinate[]; courseWaypoints: RunWaypoint[] }
export type Bookmark = { bookmarkId: string; courseId: string; name: string; courseType: 'RUNNING_COURSE' | 'SPOT_COURSE'; distanceKm: number; difficulty: 'LOW' | 'MID' | 'HIGH'; thumbnailImageUrl: string | null; mine: boolean }
export type RunTripReportSummary = { id: string; name: string; startDate: string; endDate: string; thumbnailImageUrl: string | null }
export type RunTripReportStatistics = { runCount: number; uniqueCourseCount: number; totalDistanceKm: number; totalDurationSeconds: number; averagePace: number | null; uniqueVisitedPlaceCount: number }
export type RunTripReportBreakdown = { runningCourseRuns: number; spotCourseRuns: number; freeRuns: number }
export type RunTripReportDetail = RunTripReportSummary & { statistics: RunTripReportStatistics; breakdown: RunTripReportBreakdown; runs: RunRecord[]; visits: Visit[] }
export type RunTripOverallStatistics = RunTripReportStatistics & { reportCount: number; averageDistancePerReport: number }
export type SaveRunTripReport = Pick<RunTripReportSummary, 'name' | 'startDate' | 'endDate' | 'thumbnailImageUrl'>
export type NotificationSettings = { recommendedCourse: boolean; weather: boolean; savedCourseUpdate: boolean; meetupInvite: boolean; commentLike: boolean; tierChange: boolean; eventChallenge: boolean }
