import type { ChatRoom, Meetup } from './communityTypes'

export const currentCommunityUser = {
  id: 'me',
  nickname: '러너제주',
  avatar: '러',
  gradient: 'linear-gradient(135deg,#3B82F6,#93C5FD)',
}

export const initialMeetups: Meetup[] = [
  {
    id: 'meetup-hamdeok',
    title: '함덕 새벽 바다런',
    description: '함덕 해변을 따라 가볍게 달리는 새벽 번개입니다.',
    createdAtLabel: '2시간 전',
    organizerId: 'host-1',
    organizerName: '바다러너',
    organizerAvatar: '바',
    organizerGradient: 'linear-gradient(135deg,#FF6F0F,#FF954E)',
    theme: 'COAST',
    themeLabel: '해안',
    meetupDate: '2026-08-24T06:00:00',
    scheduleLabel: '08.24 (월) 오전 6:00',
    dateKey: '2026-08-24',
    locationLabel: '함덕해수욕장',
    meetingPointLabel: '함덕 서우봉 입구',
    meetingLatitude: 33.5432,
    meetingLongitude: 126.6695,
    maxParticipants: 4,
    targetPaceLabel: `6'30" /km`,
    targetPaceValue: 6.5,
    joinMethod: 'instant',
    status: 'recruiting',
    course: {
      id: 'course-hamdeok',
      name: '함덕 감성 모닝런',
      distanceKm: 3.2,
      durationMinutes: 25,
      difficultyLabel: '쉬움',
      icon: 'R',
    },
    participantIds: ['host-1', 'runner-2'],
    applicants: [],
    myParticipation: 'accepted',
    isOrganizer: false,
  },
  {
    id: 'meetup-saryeoni',
    title: '사려니숲 힐링런',
    description: '초보 환영, 숲길 페이스 자유 번개입니다.',
    createdAtLabel: '1일 전',
    organizerId: 'host-2',
    organizerName: '숲속러너',
    organizerAvatar: '숲',
    organizerGradient: 'linear-gradient(135deg,#8B5CF6,#C4B5FD)',
    theme: 'FOREST',
    themeLabel: '숲길',
    meetupDate: '2026-08-28T08:00:00',
    scheduleLabel: '08.28 (금) 오전 8:00',
    dateKey: '2026-08-28',
    locationLabel: '사려니숲길',
    meetingPointLabel: '방문자 주차장',
    meetingLatitude: 33.4221,
    meetingLongitude: 126.6261,
    maxParticipants: 6,
    targetPaceLabel: '페이스 자유',
    targetPaceValue: null,
    joinMethod: 'approval',
    status: 'recruiting',
    course: {
      id: 'course-saryeoni',
      name: '사려니숲길 힐링런',
      distanceKm: 8.2,
      durationMinutes: 55,
      difficultyLabel: '보통',
      icon: 'R',
    },
    participantIds: ['host-2'],
    applicants: [
      {
        id: 'runner-3',
        nickname: '트레일원',
        avatar: '트',
        gradient: 'linear-gradient(135deg,#34C759,#86EFAC)',
        role: 'applicant',
        status: 'pending',
        stats: {
          totalDistanceKm: 124.5,
          averagePaceText: `6'18" /km`,
          meetupCount: 28,
        },
      },
      {
        id: 'runner-4',
        nickname: '포토스텝',
        avatar: '포',
        gradient: 'linear-gradient(135deg,#F97316,#FDBA74)',
        role: 'applicant',
        status: 'pending',
        stats: {
          totalDistanceKm: 31.2,
          averagePaceText: `7'02" /km`,
          meetupCount: 3,
        },
      },
    ],
    myParticipation: 'pending',
    isOrganizer: false,
  },
]

export const initialChatRooms: ChatRoom[] = [
  {
    id: 'chat-group-hamdeok',
    type: 'group',
    meetupId: 'meetup-hamdeok',
    title: '함덕 새벽 바다런',
    subtitle: '번개 채팅 2/4 · 08.24 06:00',
    icon: '바',
    gradient: 'linear-gradient(135deg,#FF6F0F,#FF954E)',
    unreadCount: 3,
    lastMessage: '바다러너: 6시에 집결지에서 만나요.',
    lastMessageAt: '방금',
    participantCountLabel: '2/4',
    activeDot: true,
    messages: [
      {
        id: 'm1',
        senderId: null,
        senderName: 'system',
        senderAvatar: '',
        senderGradient: '',
        content: '트레일원이 번개에 참여했습니다.',
        sentAtLabel: '2026-08-22',
        mine: false,
        system: true,
      },
      {
        id: 'm2',
        senderId: 'host-1',
        senderName: '바다러너',
        senderAvatar: '바',
        senderGradient: 'linear-gradient(135deg,#FF6F0F,#FF954E)',
        content: '집결지에서 바로 출발할게요.',
        sentAtLabel: '오전 9:14',
        mine: false,
      },
      {
        id: 'm3',
        senderId: 'me',
        senderName: '러너제주',
        senderAvatar: '러',
        senderGradient: 'linear-gradient(135deg,#3B82F6,#93C5FD)',
        content: '저도 시간 맞춰 갈게요.',
        sentAtLabel: '오전 9:41',
        mine: true,
      },
    ],
  },
]
