import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { axiosInstance } from '../../api/axiosInstance'
import { CourseListView } from '../../features/course/CourseListView'
import { courseService } from '../../features/course/courseService'
import { myPageService } from '../../features/mypage/myPageService'
import type { Dashboard, NotificationSettings, Profile, RunRecord, Trip } from '../../features/mypage/types'
import './mypage.css'

const EMPTY_PROFILE: Profile = { nickname: '러너', profileImageUrl: null, bio: null, userTypes: [], preferredDistance: null, preferredDifficulty: null, createdAt: '', accountStatus: 'ACTIVE' }
const EMPTY_DASHBOARD: Dashboard = { profile: EMPTY_PROFILE, totalDistanceKm: 0, completionCount: 0, uniqueCourseCount: 0 }
const DEFAULT_NOTIFICATIONS: NotificationSettings = { recommendedCourse: true, weather: true, savedCourseUpdate: true, meetupInvite: true, commentLike: true, tierChange: true, eventChallenge: true }
const paths: Record<string, ReactNode> = {
  back: <path d="m15 18-6-6 6-6"/>, bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>, edit: <><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z"/></>,
  history: <><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/></>, bookmark: <path d="M6 3h12v18l-6-4-6 4Z"/>, chart: <><path d="M4 19V9M10 19V5M16 19v-7M22 19V2"/></>,
  settings: <><circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 .4 2l-2.5 2.5a2 2 0 0 0-2-.4 2 2 0 0 0-1.2 1.8h-3.5A2 2 0 0 0 9 19a2 2 0 0 0-2 .4L4.5 17A2 2 0 0 0 5 15a2 2 0 0 0-1.8-1.2v-3.5A2 2 0 0 0 5 9a2 2 0 0 0-.4-2L7 4.5A2 2 0 0 0 9 5a2 2 0 0 0 1.2-1.8h3.5A2 2 0 0 0 15 5a2 2 0 0 0 2-.4L19.5 7A2 2 0 0 0 19 9a2 2 0 0 0 1.8 1.2v3.5A2 2 0 0 0 19 15Z"/></>,
  user: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>, logout: <><path d="M10 17l5-5-5-5M15 12H3"/><path d="M15 3h6v18h-6"/></>, chevron: <path d="m9 18 6-6-6-6"/>, map: <><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15M15 6v15"/></>,
}
function Icon({ name, size = 22 }: { name: string; size?: number }) { return <svg aria-hidden width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg> }
function Avatar({ profile, large = false }: { profile: Profile; large?: boolean }) { return <div className={`my-avatar ${large ? 'large' : ''}`} style={profile.profileImageUrl ? { backgroundImage: `url(${profile.profileImageUrl})` } : undefined}>{!profile.profileImageUrl && profile.nickname.slice(0, 1)}</div> }
function PageHeader({ title, action }: { title: string; action?: ReactNode }) { const navigate = useNavigate(); return <header className="my-header"><button onClick={() => navigate(-1)} aria-label="뒤로"><Icon name="back"/></button><h1>{title}</h1><div>{action}</div></header> }
function Empty({ icon = 'history', title, description, action }: { icon?: string; title: string; description: string; action?: ReactNode }) { return <div className="my-empty"><span><Icon name={icon} size={28}/></span><strong>{title}</strong><p>{description}</p>{action}</div> }
function Loading() { return <div className="my-loading"><div className="spinner"/><span>기록을 불러오는 중…</span></div> }
function formatTime(seconds: number) { const h = Math.floor(seconds / 3600), m = Math.floor(seconds % 3600 / 60), s = seconds % 60; return h ? `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}` : `${m}:${String(s).padStart(2,'0')}` }
function pace(value: number | null) { if (!value) return '-'; const min = Math.floor(value); return `${min}'${String(Math.round((value-min)*60)).padStart(2,'0')}\"` }
function imageStyle(url: string | null) { return url ? { backgroundImage: `url(${url})` } : undefined }

export function MyPage() {
  const [data, setData] = useState<Dashboard | null>(null); const [failed, setFailed] = useState(false)
  useEffect(() => { myPageService.dashboard().then(setData).catch(() => { setFailed(true); setData(EMPTY_DASHBOARD) }) }, [])
  if (!data) return <div className="my-screen"><Loading/></div>
  const { profile } = data
  return <div className="my-screen my-home"><div className="my-home-title"><h1>마이페이지</h1><Link to="/mypage/settings/notifications" aria-label="알림 설정"><Icon name="bell"/></Link></div>{failed && <p className="my-error">데이터를 불러오지 못했어요. 잠시 후 다시 시도해주세요.</p>}
    <section className="my-profile"><Link to="/mypage/settings/profile" className="avatar-edit"><Avatar profile={profile} large/><span><Icon name="edit" size={14}/></span></Link><h2>{profile.nickname}</h2><p>{profile.bio || '오늘도 나답게, 즐겁게 달려요.'}</p><em>★ {typeLabels[profile.userTypes[0]] || '러닝 입문자'}</em></section>
    <section className="my-stats"><div><span>누적 거리</span><strong>{data.totalDistanceKm.toFixed(1)}</strong><small>km</small></div><div><span>총 완주</span><strong>{data.completionCount}</strong><small>회</small></div><div><span>달린 코스</span><strong>{data.uniqueCourseCount}</strong><small>개</small></div></section>
    <nav className="my-menu"><Menu to="/mypage/history" icon="history" label="러닝 히스토리"/><Menu to="/mypage/bookmarks" icon="bookmark" label="저장한 코스"/><Menu to="/mypage/reports" icon="chart" label="런트립 리포트"/><Menu to="/mypage/settings" icon="settings" label="설정"/></nav>
  </div>
}
function Menu({ to, icon, label }: { to: string; icon: string; label: string }) { return <Link to={to}><span><Icon name={icon}/></span><b>{label}</b><Icon name="chevron" size={19}/></Link> }
function RunCard({ run }: { run: RunRecord }) { return <Link className="run-row" to={`/mypage/history/${run.id}`}><div className="thumb" style={imageStyle(run.thumbnailImageUrl)}>{!run.thumbnailImageUrl && '🏃'}</div><div><span className="type-pill">{run.courseType === 'SPOT_COURSE' ? '스팟 코스' : run.courseType ? '러닝 코스' : '자유 러닝'}</span><small>{new Date(run.startedAt).toLocaleDateString('ko-KR')}</small><h3>{run.courseName || '나만의 자유 러닝'}</h3><p><b>{run.distanceKm.toFixed(1)}km</b><i>·</i>{formatTime(run.durationSeconds)}<i>·</i>{pace(run.averagePace)}/km</p></div><Icon name="chevron" size={18}/></Link> }

export function RunningHistoryPage() { const [runs,setRuns]=useState<RunRecord[]|null>(null); useEffect(()=>{myPageService.runs().then(setRuns).catch(()=>setRuns([]))},[]); return <div className="my-screen"><PageHeader title="러닝 히스토리"/><main className="my-content"><div className="section-head"><h2>최근 완주</h2><Link to="/mypage/history/all">전체보기</Link></div>{runs===null?<Loading/>:runs.length?<div className="run-list">{runs.slice(0,3).map(r=><RunCard key={r.id} run={r}/>)}</div>:<Empty title="아직 러닝 기록이 없어요" description="첫 코스를 달리면 거리와 페이스가 여기에 기록돼요." action={<Link className="primary-link" to="/running">러닝 시작하기</Link>}/>}<div className="section-head visit-head"><h2>방문 장소</h2></div><Empty icon="map" title="기록된 방문 장소가 없어요" description="스팟 코스를 달리고 웨이포인트를 방문해보세요."/></main></div> }
export function CompletedRunsPage() { const [runs,setRuns]=useState<RunRecord[]|null>(null);const [filter,setFilter]=useState('ALL');useEffect(()=>{myPageService.runs().then(setRuns).catch(()=>setRuns([]))},[]);const filtered=useMemo(()=>runs?.filter(r=>filter==='ALL'||r.courseType===filter)??[],[runs,filter]);const distance=runs?.reduce((s,r)=>s+r.distanceKm,0)??0;return <div className="my-screen"><PageHeader title="완주 코스"/><main className="my-content"><section className="summary-cards"><div><span>총 완주</span><b>{runs?.length??0}회</b></div><div><span>달린 코스</span><b>{new Set(runs?.map(r=>r.courseId).filter(Boolean)).size}개</b></div><div><span>누적 거리</span><b>{distance.toFixed(1)}km</b></div></section><Filter value={filter} setValue={setFilter} options={[['ALL','전체'],['RUNNING_COURSE','러닝 코스'],['SPOT_COURSE','스팟 코스']]}/>{runs===null?<Loading/>:filtered.length?<div className="run-list">{filtered.map(r=><RunCard key={r.id} run={r}/>)}</div>:<Empty title="조건에 맞는 완주 기록이 없어요" description="필터를 바꾸거나 새로운 코스에 도전해보세요."/>}</main></div> }
function Filter({value,setValue,options}:{value:string;setValue:(x:string)=>void;options:string[][]}){return <div className="chips scroll">{options.map(([v,l])=><button className={value===v?'active':''} onClick={()=>setValue(v)} key={v}>{l}</button>)}</div>}

export function BookmarksPage() { return <div className="my-screen"><PageHeader title="저장한 코스"/><main className="my-content"><CourseListView scope="LIBRARY" title="저장한 코스" subtitle="내가 만든 코스와 북마크한 코스를 모아볼 수 있어요." emptyTitle="저장한 코스가 없어요" emptyDescription="코스를 만들거나 마음에 드는 코스를 저장하면 여기서 바로 확인할 수 있어요." showHeader={false} showSearch onRemoveBookmark={(bookmarkId) => myPageService.removeBookmark(bookmarkId).then(() => undefined)} onDeleteCourse={(courseId) => courseService.deleteCourse(courseId).then(() => undefined)}/></main></div> }

function TripHero({ trip }: { trip: Trip }) { return <section className="trip-hero" style={imageStyle(trip.thumbnailImageUrl)}><span>{trip.region||'여행'}</span><h2>{trip.name}</h2><p>{trip.startDate} ~ {trip.endDate}</p></section> }
function StatGrid({trip}:{trip:Trip}){return <section className="report-stat-grid"><div><span>완주 코스</span><b>{trip.completedCourses}개</b></div><div><span>달린 거리</span><b>{trip.totalDistanceKm.toFixed(1)}km</b></div><div><span>방문 장소</span><b>{trip.visitedPlaces}곳</b></div><div><span>러닝 시간</span><b>{formatTime(trip.totalDurationSeconds)}</b></div></section>}
export function ReportsPage() { const [trips,setTrips]=useState<Trip[]|null>(null);const [tab,setTab]=useState<'trip'|'all'>('trip');useEffect(()=>{myPageService.trips().then(setTrips).catch(()=>setTrips([]))},[]);const total=useMemo(()=>({courses:trips?.reduce((s,t)=>s+t.completedCourses,0)??0,distance:trips?.reduce((s,t)=>s+t.totalDistanceKm,0)??0,places:trips?.reduce((s,t)=>s+t.visitedPlaces,0)??0,time:trips?.reduce((s,t)=>s+t.totalDurationSeconds,0)??0}),[trips]);const trip=trips?.[0];return <div className="my-screen report-bg"><PageHeader title="런트립 리포트"/><div className="report-tabs"><button className={tab==='trip'?'active':''} onClick={()=>setTab('trip')}>여행별 리포트</button><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>전체 통계</button></div><main className="my-content report-content">{trips===null?<Loading/>:tab==='trip'?(trip?<><TripHero trip={trip}/><StatGrid trip={trip}/><section className="report-card"><h3>코스 경험 구성</h3><div className="ratio-bar"><i/></div><p>러닝 코스와 스팟 코스를 여행마다 균형 있게 경험해보세요.</p></section><Link className="outline-link" to="/mypage/history">러닝 히스토리 보러 가기</Link></>:<Empty icon="map" title="아직 여행 리포트가 없어요" description="여행을 만들면 기간 내 러닝 기록을 모아 보여드려요." action={<Link className="primary-link" to="/mypage/trips/new">새 여행 만들기</Link>}/>):<><h2 className="report-title">전체 런트립 통계</h2><div className="total-grid"><div><span>총 여행</span><b>{trips.length}회</b></div><div><span>총 완주 코스</span><b>{total.courses}개</b></div><div><span>총 누적 거리</span><b>{total.distance.toFixed(1)}km</b></div><div><span>총 방문 장소</span><b>{total.places}곳</b></div></div><section className="report-card"><h3>나의 러닝 브리핑</h3><p>누적 러닝 시간 <strong>{formatTime(total.time)}</strong></p><p>여행당 평균 거리 <strong>{trips.length?(total.distance/trips.length).toFixed(1):'0.0'}km</strong></p></section><Link className="outline-link" to="/mypage/trips">내 여행 기록 보기</Link></>}</main></div> }

export function TripsPage(){const [trips,setTrips]=useState<Trip[]|null>(null);useEffect(()=>{myPageService.trips().then(setTrips).catch(()=>setTrips([]))},[]);return <div className="my-screen"><PageHeader title="내 여행 기록" action={<Link className="header-action" to="/mypage/trips/new">+ 새 여행</Link>}/><main className="my-content"><div className="info-box">여행 기간 안의 러닝 기록을 모아 하나의 리포트로 정리해드려요.</div>{trips===null?<Loading/>:trips.length?<div className="trip-list">{trips.map(t=><Link to="/mypage/reports" key={t.id}><div className="thumb" style={imageStyle(t.thumbnailImageUrl)}>{!t.thumbnailImageUrl&&'🍊'}</div><div><h3>{t.name}</h3><p>{t.startDate} ~ {t.endDate} | {t.region||'지역 미지정'}</p><small>완주 {t.completedCourses}개　거리 {t.totalDistanceKm.toFixed(1)}km　방문 {t.visitedPlaces}곳</small></div><Icon name="chevron"/></Link>)}</div>:<Empty icon="map" title="저장된 여행이 없어요" description="여행 기간을 등록하고 나만의 런트립 리포트를 만들어보세요." action={<Link className="primary-link" to="/mypage/trips/new">첫 여행 만들기</Link>}/>}</main></div>}
export function TripCreatePage(){const nav=useNavigate();const [saving,setSaving]=useState(false);const [error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setSaving(true);setError('');try{await myPageService.createTrip({name:String(fd.get('name')),region:String(fd.get('region')),startDate:String(fd.get('startDate')),endDate:String(fd.get('endDate')),thumbnailImageUrl:null});nav('/mypage/trips')}catch{setError('여행을 저장하지 못했어요. 입력 내용을 확인해주세요.');setSaving(false)}};return <div className="my-screen"><PageHeader title="새 여행 만들기"/><form className="my-content trip-form" onSubmit={submit}><label>여행 이름<input required name="name" maxLength={200} placeholder="예) 2026 제주 여름 런트립"/></label><label>지역<input name="region" maxLength={100} placeholder="예) 제주"/></label><div className="date-pair"><label>시작일<input required type="date" name="startDate"/></label><label>종료일<input required type="date" name="endDate"/></label></div><div className="upload-placeholder"><Icon name="map" size={28}/><b>대표 사진은 여행 생성 후 추가할 수 있어요</b></div><div className="info-box">기간 내 완주한 코스는 이 여행 리포트에 자동으로 묶여요.</div>{error&&<p className="form-error">{error}</p>}<button className="submit-button" disabled={saving}>{saving?'저장 중…':'여행 저장하기'}</button></form></div>}

export function SettingsPage(){const nav=useNavigate();const logout=()=>{localStorage.removeItem('runningOlleAccessToken');nav('/login',{replace:true})};const withdraw=async()=>{if(!confirm('정말 회원 탈퇴할까요? 러닝 기록은 복구할 수 없을 수 있어요.'))return;await axiosInstance.delete('/users/me');logout()};return <div className="my-screen settings-bg"><PageHeader title="설정"/><main className="my-content settings-content"><SettingGroup title="계정"><Menu to="/mypage/settings/account" icon="user" label="카카오 계정 정보"/></SettingGroup><SettingGroup title="프로필"><Menu to="/mypage/settings/profile" icon="edit" label="프로필 편집"/></SettingGroup><SettingGroup title="알림"><Menu to="/mypage/settings/notifications" icon="bell" label="알림 설정"/></SettingGroup><SettingGroup title="기타"><button className="setting-button" onClick={logout}><span><Icon name="logout"/></span><b>로그아웃</b></button><button className="setting-button danger" onClick={withdraw}><span>⊘</span><b>회원 탈퇴</b></button></SettingGroup><footer><strong>Running Olle</strong><small>카카오 계정으로 안전하게 연결됨</small></footer></main></div>}
function SettingGroup({title,children}:{title:string;children:ReactNode}){return <section className="setting-group"><h2>{title}</h2><div>{children}</div></section>}
export function AccountPage(){const [p,setP]=useState<Profile|null>(null);useEffect(()=>{myPageService.profile().then(setP).catch(()=>setP(EMPTY_PROFILE))},[]);return <div className="my-screen settings-bg"><PageHeader title="계정 정보"/><main className="my-content">{!p?<Loading/>:<><section className="account-panel"><div className="account-person"><Avatar profile={p}/><div><h2>{p.nickname}</h2><p>카카오 소셜 계정</p></div></div><dl><div><dt>로그인 방식</dt><dd><i className="kakao-dot">K</i> 카카오</dd></div><div><dt>가입일</dt><dd>{p.createdAt?new Date(p.createdAt).toLocaleDateString('ko-KR'):'-'}</dd></div><div><dt>계정 상태</dt><dd><span className="status-pill">정상</span></dd></div></dl></section><div className="info-box">러닝올레는 카카오 로그인만 지원합니다. 비밀번호와 카카오 계정 정보는 카카오에서 안전하게 관리돼요.</div><a className="outline-link" href="https://accounts.kakao.com" target="_blank" rel="noreferrer">카카오 계정 관리 열기</a></>}</main></div>}

const typeLabels:Record<string,string>={ACTIVE_RUNNER:'활동적인 러너',RELAXED_TRAVELER:'여유로운 여행자',JEJU_RESIDENT:'제주 거주민'}
export function ProfileEditPage(){const nav=useNavigate();const [p,setP]=useState<Profile|null>(null);const [saving,setSaving]=useState(false);useEffect(()=>{myPageService.profile().then(setP).catch(()=>setP(EMPTY_PROFILE))},[]);if(!p)return <div className="my-screen"><Loading/></div>;const save=async()=>{setSaving(true);try{await myPageService.updateProfile(p);nav('/mypage')}catch{setSaving(false);alert('프로필을 저장하지 못했어요.')}};return <div className="my-screen settings-bg"><PageHeader title="프로필 편집" action={<button className="save-text" onClick={save} disabled={saving}>{saving?'저장 중':'저장'}</button>}/><main className="my-content profile-form"><div className="profile-avatar"><Avatar profile={p} large/><span><Icon name="edit" size={15}/></span></div><label>닉네임<input value={p.nickname} maxLength={100} onChange={e=>setP({...p,nickname:e.target.value})}/></label><label>자기소개<textarea value={p.bio||''} maxLength={300} onChange={e=>setP({...p,bio:e.target.value})}/></label><Choice title="사용자 유형" options={['ACTIVE_RUNNER','RELAXED_TRAVELER','JEJU_RESIDENT']} value={p.userTypes[0]||''} labels={typeLabels} onChange={v=>setP({...p,userTypes:[v]})}/><Choice title="선호 거리" options={['UNDER_3KM','FROM_5_TO_10KM','OVER_10KM']} value={p.preferredDistance||''} labels={{UNDER_3KM:'3km 이하',FROM_5_TO_10KM:'5km ~ 10km',OVER_10KM:'10km 이상'}} onChange={v=>setP({...p,preferredDistance:v})}/><Choice title="선호 난이도" options={['EASY','NORMAL','HARD']} value={p.preferredDifficulty||''} labels={{EASY:'쉬움',NORMAL:'보통',HARD:'어려움'}} onChange={v=>setP({...p,preferredDifficulty:v})}/><button className="submit-button" onClick={save} disabled={saving}>저장하기</button></main></div>}
function Choice({title,options,value,labels,onChange}:{title:string;options:string[];value:string;labels:Record<string,string>;onChange:(v:string)=>void}){return <section className="profile-choice"><h2>{title}</h2><div className="chips">{options.map(x=><button className={value===x?'active':''} onClick={()=>onChange(x)} key={x}>{labels[x]}</button>)}</div></section>}
export function NotificationPage(){const [settings,setSettings]=useState<NotificationSettings|null>(null);const [saved,setSaved]=useState(false);useEffect(()=>{myPageService.notifications().then(setSettings).catch(()=>setSettings(DEFAULT_NOTIFICATIONS))},[]);const toggle=async(key:keyof NotificationSettings)=>{if(!settings)return;const next={...settings,[key]:!settings[key]};setSettings(next);setSaved(false);try{await myPageService.updateNotifications(next);setSaved(true);setTimeout(()=>setSaved(false),1500)}catch{setSettings(settings)}};if(!settings)return <div className="my-screen"><Loading/></div>;return <div className="my-screen settings-bg"><PageHeader title="알림 설정"/><main className="my-content notification-content"><div className="info-box">러닝과 여행에 꼭 필요한 소식만 골라 받을 수 있어요.</div><ToggleGroup title="코스 및 기상" rows={[['recommendedCourse','추천 코스','나에게 맞는 코스 추천'],['weather','날씨 주의','폭염·강수 등 러닝 주의 알림']]} settings={settings} toggle={toggle}/><ToggleGroup title="소셜 및 활동" rows={[['savedCourseUpdate','저장 코스','저장한 코스의 변경 소식'],['meetupInvite','같이 달리기','모임 초대 및 일정 알림'],['commentLike','댓글/좋아요','내 활동에 대한 반응 알림']]} settings={settings} toggle={toggle}/><ToggleGroup title="혜택 및 성장" rows={[['tierChange','티어 변경','등급 상승과 배지 소식'],['eventChallenge','이벤트/챌린지','시즌 이벤트와 챌린지 소식']]} settings={settings} toggle={toggle}/>{saved&&<div className="save-toast">알림 설정을 저장했어요</div>}</main></div>}
function ToggleGroup({title,rows,settings,toggle}:{title:string;rows:[keyof NotificationSettings,string,string][];settings:NotificationSettings;toggle:(k:keyof NotificationSettings)=>void}){return <section className="toggle-group"><h2>{title}</h2><div>{rows.map(([key,label,desc])=><button key={key} onClick={()=>toggle(key)}><span><b>{label}</b><small>{desc}</small></span><i className={settings[key]?'on':''}><em/></i></button>)}</div></section>}
