package com.runningolle.global.security.oauth;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;
import lombok.RequiredArgsConstructor;
import org.springframework.security.oauth2.client.web.AuthorizationRequestRepository;
import org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationRequest;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

/**
 * Stores each authorization request by its state parameter in the database.
 *
 * <p>The OAuth round trip must survive backend restarts and must not depend on a
 * browser session cookie. The state value is a cryptographically random CSRF
 * token generated by Spring Security and is used as the lookup key.</p>
 */
@Component
@RequiredArgsConstructor
public class StateAwareOAuth2AuthorizationRequestRepository
        implements AuthorizationRequestRepository<OAuth2AuthorizationRequest> {

    private static final Duration REQUEST_TTL = Duration.ofMinutes(10);

    private final OAuthAuthorizationRequestStateRepository stateRepository;

    @Override
    @Transactional
    public OAuth2AuthorizationRequest loadAuthorizationRequest(HttpServletRequest request) {
        String state = request.getParameter("state");
        if (!StringUtils.hasText(state)) {
            return null;
        }

        Instant now = Instant.now();
        return stateRepository.findById(state)
                .filter(saved -> !removeIfExpired(saved, now))
                .map(saved -> deserialize(saved.getPayload()))
                .orElse(null);
    }

    @Override
    @Transactional
    public void saveAuthorizationRequest(
            OAuth2AuthorizationRequest authorizationRequest,
            HttpServletRequest request,
            HttpServletResponse response
    ) {
        if (authorizationRequest == null) {
            removeAuthorizationRequest(request, response);
            return;
        }

        String state = authorizationRequest.getState();
        if (!StringUtils.hasText(state)) {
            throw new IllegalArgumentException("authorizationRequest.state cannot be empty");
        }

        Instant now = Instant.now();
        stateRepository.deleteByExpiresAtBefore(now);
        stateRepository.save(new OAuthAuthorizationRequestState(
                state,
                serialize(authorizationRequest),
                now.plus(REQUEST_TTL)
        ));
    }

    @Override
    @Transactional
    public OAuth2AuthorizationRequest removeAuthorizationRequest(
            HttpServletRequest request,
            HttpServletResponse response
    ) {
        String state = request.getParameter("state");
        if (!StringUtils.hasText(state)) {
            return null;
        }

        OAuthAuthorizationRequestState saved = stateRepository.findByStateForUpdate(state).orElse(null);
        if (saved == null) {
            return null;
        }
        stateRepository.deleteById(state);

        if (saved.isExpired(Instant.now())) {
            return null;
        }
        return deserialize(saved.getPayload());
    }

    private boolean removeIfExpired(OAuthAuthorizationRequestState saved, Instant now) {
        if (!saved.isExpired(now)) {
            return false;
        }
        stateRepository.deleteById(saved.getState());
        return true;
    }

    private String serialize(OAuth2AuthorizationRequest authorizationRequest) {
        try (ByteArrayOutputStream bytes = new ByteArrayOutputStream();
             ObjectOutputStream output = new ObjectOutputStream(bytes)) {
            output.writeObject(authorizationRequest);
            return Base64.getEncoder().encodeToString(bytes.toByteArray());
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to store OAuth authorization request", exception);
        }
    }

    private OAuth2AuthorizationRequest deserialize(String payload) {
        try (ObjectInputStream input = new ObjectInputStream(
                new ByteArrayInputStream(Base64.getDecoder().decode(payload)))) {
            Object value = input.readObject();
            if (value instanceof OAuth2AuthorizationRequest authorizationRequest) {
                return authorizationRequest;
            }
            throw new IllegalStateException("Stored OAuth authorization request has an invalid type");
        } catch (IOException | ClassNotFoundException | IllegalArgumentException exception) {
            throw new IllegalStateException("Failed to read OAuth authorization request", exception);
        }
    }
}
